name: Tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build:
    name: Test suite
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:latest

    steps:
      - name : Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
      - name: Run examples
        run: |
          crystal run examples/test.cr
          crystal run examples/test2.cr
